### ISSUE TITLE
Sample Unit Test Code?

### ISSUE THREAD

**Issue by jprogersiii** [poulfoged/redis-inside#1]
This project looks very interesting. Could you please provide some sample unit test code, showing how I can use this inside a unit test? Thanks!

**Comment by poulfoged** [comment]
There is some code in the readme - it's as easy as:

``` csharp
using (var redis = new Redis())
{
    // connect to redis.Endpoint here
}
```

See more samples here: 
https://github.com/poulfoged/redis-inside/blob/master/source/RedisInside.Tests/RedisTests.cs
