### ISSUE TITLE
Signed version of Nuget package

### ISSUE THREAD

**Issue by IlyaGrebnov** [poulfoged/redis-inside#2]
Roslyn give warning CS8002 for using unsigned references from signed (delay-signed more specifically) assemblies. Is any way you could create signed version of Nuget package(similar to StackExchange.Redis.StrongName)?

Note, delay-signed test assemblies allow me reference internals from productions signed code using InternalsVisibleTo attribute, so this is important scenario for me.

**Comment by poulfoged** [comment]
Hello, is this still relevant?
