### ISSUE TITLE
Change target framework from of 4.5.1 to 4.5

### ISSUE THREAD

**Issue by IlyaGrebnov** [poulfoged/redis-inside#3]
You seams to me not using any of .net 4.5.1 specific feature. So could you please change target framework from of 4.5.1 to 4.5, so exiting project targeting just 4.5 could consume nuget.

**Comment by poulfoged** [comment]
Hello, is this still relevant?

**Comment by Hammerstad** [comment]
Considering Microsoft has ended support for 4.5 and 4.5.1, probably not.

Source https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/
