### ISSUE TITLE
Support dotnet core?

### ISSUE THREAD

**Issue by nripendra** [poulfoged/redis-inside#6]
Are there any plans?

**Comment by poulfoged** [comment]
Yes eventually.

But it would still just be for win64 right?

**Comment by damianh** [comment]
Would like linux also.

**Comment by mkontula** [comment]
I tested the library with Core2.0 on Win64 and it works like a charm. Any chance of releasing a new version which would natively target Core2.0? It would make the nasty dependency warning go away.

**Comment by poulfoged** [comment]
@naile Has done the work! A new release is on the nuget feed.
